// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ItemViewCountProto.proto

package com.at.proto;

public final class ItemViewCountProto {
  private ItemViewCountProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItemViewCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.at.proto.ItemViewCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 itemId = 1;</code>
     * @return The itemId.
     */
    long getItemId();

    /**
     * <code>int64 windowStart = 2;</code>
     * @return The windowStart.
     */
    long getWindowStart();

    /**
     * <code>int64 windowEnd = 3;</code>
     * @return The windowEnd.
     */
    long getWindowEnd();

    /**
     * <code>int64 count = 4;</code>
     * @return The count.
     */
    long getCount();
  }
  /**
   * Protobuf type {@code com.at.proto.ItemViewCount}
   */
  public static final class ItemViewCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.at.proto.ItemViewCount)
      ItemViewCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItemViewCount.newBuilder() to construct.
    private ItemViewCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItemViewCount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ItemViewCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItemViewCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              itemId_ = input.readInt64();
              break;
            }
            case 16: {

              windowStart_ = input.readInt64();
              break;
            }
            case 24: {

              windowEnd_ = input.readInt64();
              break;
            }
            case 32: {

              count_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.at.proto.ItemViewCountProto.internal_static_com_at_proto_ItemViewCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.at.proto.ItemViewCountProto.internal_static_com_at_proto_ItemViewCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.at.proto.ItemViewCountProto.ItemViewCount.class, com.at.proto.ItemViewCountProto.ItemViewCount.Builder.class);
    }

    public static final int ITEMID_FIELD_NUMBER = 1;
    private long itemId_;
    /**
     * <code>int64 itemId = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public long getItemId() {
      return itemId_;
    }

    public static final int WINDOWSTART_FIELD_NUMBER = 2;
    private long windowStart_;
    /**
     * <code>int64 windowStart = 2;</code>
     * @return The windowStart.
     */
    @java.lang.Override
    public long getWindowStart() {
      return windowStart_;
    }

    public static final int WINDOWEND_FIELD_NUMBER = 3;
    private long windowEnd_;
    /**
     * <code>int64 windowEnd = 3;</code>
     * @return The windowEnd.
     */
    @java.lang.Override
    public long getWindowEnd() {
      return windowEnd_;
    }

    public static final int COUNT_FIELD_NUMBER = 4;
    private long count_;
    /**
     * <code>int64 count = 4;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (itemId_ != 0L) {
        output.writeInt64(1, itemId_);
      }
      if (windowStart_ != 0L) {
        output.writeInt64(2, windowStart_);
      }
      if (windowEnd_ != 0L) {
        output.writeInt64(3, windowEnd_);
      }
      if (count_ != 0L) {
        output.writeInt64(4, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (itemId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, itemId_);
      }
      if (windowStart_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, windowStart_);
      }
      if (windowEnd_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, windowEnd_);
      }
      if (count_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.at.proto.ItemViewCountProto.ItemViewCount)) {
        return super.equals(obj);
      }
      com.at.proto.ItemViewCountProto.ItemViewCount other = (com.at.proto.ItemViewCountProto.ItemViewCount) obj;

      if (getItemId()
          != other.getItemId()) return false;
      if (getWindowStart()
          != other.getWindowStart()) return false;
      if (getWindowEnd()
          != other.getWindowEnd()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ITEMID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getItemId());
      hash = (37 * hash) + WINDOWSTART_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWindowStart());
      hash = (37 * hash) + WINDOWEND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWindowEnd());
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCount());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.at.proto.ItemViewCountProto.ItemViewCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.at.proto.ItemViewCountProto.ItemViewCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.at.proto.ItemViewCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.at.proto.ItemViewCount)
        com.at.proto.ItemViewCountProto.ItemViewCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.at.proto.ItemViewCountProto.internal_static_com_at_proto_ItemViewCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.at.proto.ItemViewCountProto.internal_static_com_at_proto_ItemViewCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.at.proto.ItemViewCountProto.ItemViewCount.class, com.at.proto.ItemViewCountProto.ItemViewCount.Builder.class);
      }

      // Construct using com.at.proto.ItemViewCountProto.ItemViewCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        itemId_ = 0L;

        windowStart_ = 0L;

        windowEnd_ = 0L;

        count_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.at.proto.ItemViewCountProto.internal_static_com_at_proto_ItemViewCount_descriptor;
      }

      @java.lang.Override
      public com.at.proto.ItemViewCountProto.ItemViewCount getDefaultInstanceForType() {
        return com.at.proto.ItemViewCountProto.ItemViewCount.getDefaultInstance();
      }

      @java.lang.Override
      public com.at.proto.ItemViewCountProto.ItemViewCount build() {
        com.at.proto.ItemViewCountProto.ItemViewCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.at.proto.ItemViewCountProto.ItemViewCount buildPartial() {
        com.at.proto.ItemViewCountProto.ItemViewCount result = new com.at.proto.ItemViewCountProto.ItemViewCount(this);
        result.itemId_ = itemId_;
        result.windowStart_ = windowStart_;
        result.windowEnd_ = windowEnd_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.at.proto.ItemViewCountProto.ItemViewCount) {
          return mergeFrom((com.at.proto.ItemViewCountProto.ItemViewCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.at.proto.ItemViewCountProto.ItemViewCount other) {
        if (other == com.at.proto.ItemViewCountProto.ItemViewCount.getDefaultInstance()) return this;
        if (other.getItemId() != 0L) {
          setItemId(other.getItemId());
        }
        if (other.getWindowStart() != 0L) {
          setWindowStart(other.getWindowStart());
        }
        if (other.getWindowEnd() != 0L) {
          setWindowEnd(other.getWindowEnd());
        }
        if (other.getCount() != 0L) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.at.proto.ItemViewCountProto.ItemViewCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.at.proto.ItemViewCountProto.ItemViewCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long itemId_ ;
      /**
       * <code>int64 itemId = 1;</code>
       * @return The itemId.
       */
      @java.lang.Override
      public long getItemId() {
        return itemId_;
      }
      /**
       * <code>int64 itemId = 1;</code>
       * @param value The itemId to set.
       * @return This builder for chaining.
       */
      public Builder setItemId(long value) {
        
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 itemId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemId() {
        
        itemId_ = 0L;
        onChanged();
        return this;
      }

      private long windowStart_ ;
      /**
       * <code>int64 windowStart = 2;</code>
       * @return The windowStart.
       */
      @java.lang.Override
      public long getWindowStart() {
        return windowStart_;
      }
      /**
       * <code>int64 windowStart = 2;</code>
       * @param value The windowStart to set.
       * @return This builder for chaining.
       */
      public Builder setWindowStart(long value) {
        
        windowStart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 windowStart = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindowStart() {
        
        windowStart_ = 0L;
        onChanged();
        return this;
      }

      private long windowEnd_ ;
      /**
       * <code>int64 windowEnd = 3;</code>
       * @return The windowEnd.
       */
      @java.lang.Override
      public long getWindowEnd() {
        return windowEnd_;
      }
      /**
       * <code>int64 windowEnd = 3;</code>
       * @param value The windowEnd to set.
       * @return This builder for chaining.
       */
      public Builder setWindowEnd(long value) {
        
        windowEnd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 windowEnd = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindowEnd() {
        
        windowEnd_ = 0L;
        onChanged();
        return this;
      }

      private long count_ ;
      /**
       * <code>int64 count = 4;</code>
       * @return The count.
       */
      @java.lang.Override
      public long getCount() {
        return count_;
      }
      /**
       * <code>int64 count = 4;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(long value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.at.proto.ItemViewCount)
    }

    // @@protoc_insertion_point(class_scope:com.at.proto.ItemViewCount)
    private static final com.at.proto.ItemViewCountProto.ItemViewCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.at.proto.ItemViewCountProto.ItemViewCount();
    }

    public static com.at.proto.ItemViewCountProto.ItemViewCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItemViewCount>
        PARSER = new com.google.protobuf.AbstractParser<ItemViewCount>() {
      @java.lang.Override
      public ItemViewCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemViewCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItemViewCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItemViewCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.at.proto.ItemViewCountProto.ItemViewCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_at_proto_ItemViewCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_at_proto_ItemViewCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036proto/ItemViewCountProto.proto\022\014com.at" +
      ".proto\"V\n\rItemViewCount\022\016\n\006itemId\030\001 \001(\003\022" +
      "\023\n\013windowStart\030\002 \001(\003\022\021\n\twindowEnd\030\003 \001(\003\022" +
      "\r\n\005count\030\004 \001(\003B)\n\014com.at.protoB\022ItemView" +
      "CountProtoH\001P\000\330\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_at_proto_ItemViewCount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_at_proto_ItemViewCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_at_proto_ItemViewCount_descriptor,
        new java.lang.String[] { "ItemId", "WindowStart", "WindowEnd", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
