
server:
  port: 10086
  name: test-yaml-application

kafka:
  brocker:
    gb16-brocker: hadoop102:9092,hadoop103:9092,hadoop104:9092
    gb17-brocker: k8s01:9092,k8s02:9092,k8s03:9092
  topic:
    app:
      click: PRODUCTION_app_click_topic
      impression: PRODUCTION_app_impression_topic
    wechat:
      click: PRODUCTION_wechat_click_topic
      impression: PRODUCTION_wechat_impression_topic
    h5-wap: PRODUCTION_h5wap_topic


zookeeper:
  server: hadoop102:2181,hadoop103:2181,hadoop104:2181
  listerer-topic: 9870

redis:
  port: 6379



