// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SelfDescribingMessage.proto

package com.at.proto;

public final class SelfDescribingMessageProto {
  private SelfDescribingMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SelfDescribingMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SelfDescribingMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return Whether the descriptorSet field is set.
     */
    boolean hasDescriptorSet();
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return The descriptorSet.
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet();
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder();

    /**
     * <code>string msg_name = 2;</code>
     * @return The msgName.
     */
    java.lang.String getMsgName();
    /**
     * <code>string msg_name = 2;</code>
     * @return The bytes for msgName.
     */
    com.google.protobuf.ByteString
        getMsgNameBytes();

    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>bytes message = 3;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();
  }
  /**
   * Protobuf type {@code SelfDescribingMessage}
   */
  public static final class SelfDescribingMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SelfDescribingMessage)
      SelfDescribingMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SelfDescribingMessage.newBuilder() to construct.
    private SelfDescribingMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SelfDescribingMessage() {
      msgName_ = "";
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SelfDescribingMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SelfDescribingMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder subBuilder = null;
              if (descriptorSet_ != null) {
                subBuilder = descriptorSet_.toBuilder();
              }
              descriptorSet_ = input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorSet.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(descriptorSet_);
                descriptorSet_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgName_ = s;
              break;
            }
            case 26: {

              message_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.at.proto.SelfDescribingMessageProto.internal_static_SelfDescribingMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.at.proto.SelfDescribingMessageProto.internal_static_SelfDescribingMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.class, com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.Builder.class);
    }

    public static final int DESCRIPTOR_SET_FIELD_NUMBER = 1;
    private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_;
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return Whether the descriptorSet field is set.
     */
    @java.lang.Override
    public boolean hasDescriptorSet() {
      return descriptorSet_ != null;
    }
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     * @return The descriptorSet.
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
      return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
    }
    /**
     * <pre>
     * Set of FileDescriptorProtos which describe the type and its dependencies.
     * </pre>
     *
     * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
      return getDescriptorSet();
    }

    public static final int MSG_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgName_;
    /**
     * <code>string msg_name = 2;</code>
     * @return The msgName.
     */
    @java.lang.Override
    public java.lang.String getMsgName() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgName_ = s;
        return s;
      }
    }
    /**
     * <code>string msg_name = 2;</code>
     * @return The bytes for msgName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString message_;
    /**
     * <pre>
     * The message and its type, encoded as an Any message.
     * </pre>
     *
     * <code>bytes message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasDescriptorSet()) {
        if (!getDescriptorSet().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (descriptorSet_ != null) {
        output.writeMessage(1, getDescriptorSet());
      }
      if (!getMsgNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgName_);
      }
      if (!message_.isEmpty()) {
        output.writeBytes(3, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (descriptorSet_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDescriptorSet());
      }
      if (!getMsgNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgName_);
      }
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage)) {
        return super.equals(obj);
      }
      com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage other = (com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage) obj;

      if (hasDescriptorSet() != other.hasDescriptorSet()) return false;
      if (hasDescriptorSet()) {
        if (!getDescriptorSet()
            .equals(other.getDescriptorSet())) return false;
      }
      if (!getMsgName()
          .equals(other.getMsgName())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDescriptorSet()) {
        hash = (37 * hash) + DESCRIPTOR_SET_FIELD_NUMBER;
        hash = (53 * hash) + getDescriptorSet().hashCode();
      }
      hash = (37 * hash) + MSG_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMsgName().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SelfDescribingMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SelfDescribingMessage)
        com.at.proto.SelfDescribingMessageProto.SelfDescribingMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.at.proto.SelfDescribingMessageProto.internal_static_SelfDescribingMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.at.proto.SelfDescribingMessageProto.internal_static_SelfDescribingMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.class, com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.Builder.class);
      }

      // Construct using com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
        } else {
          descriptorSet_ = null;
          descriptorSetBuilder_ = null;
        }
        msgName_ = "";

        message_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.at.proto.SelfDescribingMessageProto.internal_static_SelfDescribingMessage_descriptor;
      }

      @java.lang.Override
      public com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage getDefaultInstanceForType() {
        return com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage build() {
        com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage buildPartial() {
        com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage result = new com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage(this);
        if (descriptorSetBuilder_ == null) {
          result.descriptorSet_ = descriptorSet_;
        } else {
          result.descriptorSet_ = descriptorSetBuilder_.build();
        }
        result.msgName_ = msgName_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage) {
          return mergeFrom((com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage other) {
        if (other == com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage.getDefaultInstance()) return this;
        if (other.hasDescriptorSet()) {
          mergeDescriptorSet(other.getDescriptorSet());
        }
        if (!other.getMsgName().isEmpty()) {
          msgName_ = other.msgName_;
          onChanged();
        }
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasDescriptorSet()) {
          if (!getDescriptorSet().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.DescriptorProtos.FileDescriptorSet descriptorSet_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> descriptorSetBuilder_;
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       * @return Whether the descriptorSet field is set.
       */
      public boolean hasDescriptorSet() {
        return descriptorSetBuilder_ != null || descriptorSet_ != null;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       * @return The descriptorSet.
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet getDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          return descriptorSet_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        } else {
          return descriptorSetBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          descriptorSet_ = value;
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder setDescriptorSet(
          com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder builderForValue) {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = builderForValue.build();
          onChanged();
        } else {
          descriptorSetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder mergeDescriptorSet(com.google.protobuf.DescriptorProtos.FileDescriptorSet value) {
        if (descriptorSetBuilder_ == null) {
          if (descriptorSet_ != null) {
            descriptorSet_ =
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder(descriptorSet_).mergeFrom(value).buildPartial();
          } else {
            descriptorSet_ = value;
          }
          onChanged();
        } else {
          descriptorSetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public Builder clearDescriptorSet() {
        if (descriptorSetBuilder_ == null) {
          descriptorSet_ = null;
          onChanged();
        } else {
          descriptorSet_ = null;
          descriptorSetBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder getDescriptorSetBuilder() {
        
        onChanged();
        return getDescriptorSetFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder getDescriptorSetOrBuilder() {
        if (descriptorSetBuilder_ != null) {
          return descriptorSetBuilder_.getMessageOrBuilder();
        } else {
          return descriptorSet_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorSet.getDefaultInstance() : descriptorSet_;
        }
      }
      /**
       * <pre>
       * Set of FileDescriptorProtos which describe the type and its dependencies.
       * </pre>
       *
       * <code>.google.protobuf.FileDescriptorSet descriptor_set = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder> 
          getDescriptorSetFieldBuilder() {
        if (descriptorSetBuilder_ == null) {
          descriptorSetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorSet, com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorSetOrBuilder>(
                  getDescriptorSet(),
                  getParentForChildren(),
                  isClean());
          descriptorSet_ = null;
        }
        return descriptorSetBuilder_;
      }

      private java.lang.Object msgName_ = "";
      /**
       * <code>string msg_name = 2;</code>
       * @return The msgName.
       */
      public java.lang.String getMsgName() {
        java.lang.Object ref = msgName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg_name = 2;</code>
       * @return The bytes for msgName.
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        java.lang.Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg_name = 2;</code>
       * @param value The msgName to set.
       * @return This builder for chaining.
       */
      public Builder setMsgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgName() {
        
        msgName_ = getDefaultInstance().getMsgName();
        onChanged();
        return this;
      }
      /**
       * <code>string msg_name = 2;</code>
       * @param value The bytes for msgName to set.
       * @return This builder for chaining.
       */
      public Builder setMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>bytes message = 3;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>bytes message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The message and its type, encoded as an Any message.
       * </pre>
       *
       * <code>bytes message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SelfDescribingMessage)
    }

    // @@protoc_insertion_point(class_scope:SelfDescribingMessage)
    private static final com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage();
    }

    public static com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SelfDescribingMessage>
        PARSER = new com.google.protobuf.AbstractParser<SelfDescribingMessage>() {
      @java.lang.Override
      public SelfDescribingMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SelfDescribingMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SelfDescribingMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SelfDescribingMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.at.proto.SelfDescribingMessageProto.SelfDescribingMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SelfDescribingMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SelfDescribingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033SelfDescribingMessage.proto\032 google/pr" +
      "otobuf/descriptor.proto\"v\n\025SelfDescribin" +
      "gMessage\022:\n\016descriptor_set\030\001 \001(\0132\".googl" +
      "e.protobuf.FileDescriptorSet\022\020\n\010msg_name" +
      "\030\002 \001(\t\022\017\n\007message\030\003 \001(\014B,\n\014com.at.protoB" +
      "\032SelfDescribingMessageProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_SelfDescribingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SelfDescribingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SelfDescribingMessage_descriptor,
        new java.lang.String[] { "DescriptorSet", "MsgName", "Message", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
